---
  name: Check code

  on:
    workflow_call:

  jobs:
    check_code:
      name: Check code
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.12"]

      steps:
        - name: Check out repository
          uses: actions/checkout@v4.2.1
          with:
            fetch-depth: 0

        - name: Check if commit messages are compliant
          uses: webiny/action-conventional-commits@v1.3.0
          with:
            allowed-commit-types: "feat,fix,docs,style,refactor,perf,test,chore,bug,build,ci,bump"

        - name: Install uv
          uses: astral-sh/setup-uv@v3.1.4
          with:
            enable-cache: true

        - name: Set up Python ${{ matrix.python-version }}
          run: uv python install ${{ matrix.python-version }}

        - name: Install the project
          run: uv sync --all-extras --dev

        - name: Check code
          run: uv run ruff check .

        - name: Check code format
          run: uv run ruff format --check .

        - name: Type check using mypy
          run: uv run mypy .

    success:
      name: Check code passed
      runs-on: ubuntu-latest
      needs: [check_code]
      steps:
        - name: Decide whether the needed jobs succeeded or failed
          uses: re-actors/alls-green@v1.2.2
          with:
            jobs: ${{ toJSON(needs) }}

