---
name: Create release

on: workflow_dispatch

jobs:
  test_code:
    name: test code
    uses: ./.github/workflows/test_code.yml

  create_release:
    name: Create release
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.12"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.0

      - name: Temporarily disable 'include administrators' default branch protection
        uses: benjefferies/branch-protection-bot@v1.1.2
        if: always()
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          branch: ${{ github.event.repository.default_branch }}
          enforce_admins: false

      - name: Update license year
        uses: FantasticFiasco/action-update-license-year@v3.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge license year pull request
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --squash --delete-branch --admin

      - name: Bump version and create changelog
        uses: commitizen-tools/commitizen-action@0.21.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md

      - name: Restore 'include administrators' default branch protection
        uses: benjefferies/branch-protection-bot@v1.1.2
        if: always()
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          owner: ${{ github.event.repository.owner }}
          repo: ${{ github.event.repository.name }}
          branch: ${{ github.event.repository.default_branch }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3.1.2
        with:
          enable-cache: true

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        run: uv python install ${{ env.PYTHON_VERSION }}

      - name: Install the project
        run: uv sync --dev

      - name: Build python package
        run: uv build

      - name: Create github release
        uses: softprops/action-gh-release@v2.0.8
        with:
          body_path: body.md
          files: |
            dist/*.whl
            dist/*.tar.gz
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
